INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Nissan', 'NGK', 416.43, 81);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa BMW', 'Delphi', 170.04, 46);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Renault', 'Hella', 478.98, 64);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Peugeot', 'Delphi', 497.69, 88);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Jeep', 'Bilstein', 265.8, 19);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Kia', 'Hella', 193.15, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Kia', 'Boge', 20.51, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Ford', 'SKF', 421.33, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Nissan', 'Delphi', 146.1, 74);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Chevrolet', 'BOSCH', 417.25, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Renault', 'Brembo', 465.48, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'Denso', 169.09, 70);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Honda', 'Brembo', 26.61, 84);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Nissan', 'Bosch', 207.95, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Kia', 'Delphi', 292.18, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Mercedes', 'Bosch', 292.45, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Toyota', 'SKF', 62.9, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Fiat', 'Delphi', 266.77, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Renault', 'Valeo', 471.88, 7);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Mazda', 'Denso', 436.09, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Jeep', 'Bilstein', 88.43, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Hyundai', 'Valeo', 16.94, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Renault', 'TRW', 358.98, 36);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Opel', 'BOSCH', 135.93, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Subaru', 'Lucas', 384.05, 21);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Jeep', 'Varta', 484.66, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Kia', 'Hella', 230.1, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Toyota', 'Denso', 355.66, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Ford', 'SKF', 140.58, 19);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Ford', 'NGK', 169.79, 99);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Honda', 'Zimmermann', 283.02, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Land Rover', 'Lucas', 419.75, 88);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Subaru', 'Hella', 37.72, 51);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Honda', 'Valeo', 221.12, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Volkswagen', 'Lucas', 149.29, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Porsche', 'Sachs', 308.15, 35);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Volkswagen', 'Varta', 203.05, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Mercedes', 'Boge', 337.44, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Subaru', 'NGK', 355.55, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Chevrolet', 'Lucas', 44.13, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Toyota', 'Mahle', 485.98, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Mercedes', 'Bosch', 441.14, 81);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju BMW', 'Varta', 240.93, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Subaru', 'Hella', 252.12, 99);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Audi', 'Sachs', 34.22, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Peugeot', 'Brembo', 334.51, 56);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Opel', 'Varta', 78.75, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Audi', 'NGK', 346.35, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Land Rover', 'SKF', 218.77, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'BOSCH', 234.87, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Toyota', 'Bosch', 51.62, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi BMW', 'Zimmermann', 461.93, 51);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Hyundai', 'Sachs', 93.52, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Opel', 'TRW', 204.95, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Subaru', 'Zimmermann', 285.64, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Subaru', 'Boge', 310.42, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Renault', 'Mann Filter', 497.7, 71);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Land Rover', 'Valeo', 342.71, 68);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Peugeot', 'TRW', 33.92, 44);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Chevrolet', 'SKF', 121.64, 10);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Ford', 'Valeo', 224.8, 16);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Hyundai', 'SKF', 91.48, 2);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Subaru', 'Bilstein', 395.39, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Renault', 'BOSCH', 25.19, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Hyundai', 'Zimmermann', 142.28, 74);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Chevrolet', 'Sachs', 136.92, 35);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Porsche', 'Denso', 386.78, 28);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Ford', 'Valeo', 433.43, 56);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa BMW', 'Lucas', 256.52, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa BMW', 'Brembo', 382.32, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Fiat', 'Monroe', 486.72, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Volkswagen', 'Bilstein', 315.7, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Nissan', 'Varta', 44.46, 20);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Mazda', 'Bosch', 386.77, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Mazda', 'SKF', 131.38, 58);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Honda', 'Sachs', 396.18, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Audi', 'Monroe', 444.74, 35);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Ford', 'Delphi', 82.71, 77);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Porsche', 'Delphi', 323.23, 8);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Kia', 'Delphi', 20.5, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Hyundai', 'Monroe', 260.37, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Ford', 'Mann Filter', 221.77, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Fiat', 'Valeo', 22.7, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Hyundai', 'Sachs', 369.15, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Honda', 'Sachs', 77.5, 39);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Audi', 'TRW', 208.57, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Toyota', 'Varta', 287.29, 81);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Opel', 'BOSCH', 334.24, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Jeep', 'Mahle', 273.33, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Mercedes', 'Monroe', 248.5, 92);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Porsche', 'Lucas', 41.87, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Ford', 'Lucas', 460.02, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Subaru', 'Febi Bilstein', 58.17, 63);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Kia', 'Brembo', 427.99, 100);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Nissan', 'Mann Filter', 414.77, 19);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Hyundai', 'Mahle', 95.15, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Audi', 'Mahle', 166.2, 98);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy BMW', 'Hella', 215.45, 56);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Kia', 'Bosch', 187.14, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Porsche', 'Monroe', 404.86, 2);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury BMW', 'Mahle', 52.69, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Toyota', 'Delphi', 234.02, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Volkswagen', 'Boge', 476.64, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Hyundai', 'NGK', 458.83, 71);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Fiat', 'Mann Filter', 260.01, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Subaru', 'Varta', 463.63, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Ford', 'NGK', 382.17, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Mercedes', 'SKF', 402.12, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Nissan', 'Febi Bilstein', 480.89, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Opel', 'NGK', 134.59, 30);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Ford', 'Delphi', 128.96, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Honda', 'Febi Bilstein', 262.92, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Mazda', 'Valeo', 158.42, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Subaru', 'Denso', 192.66, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Volkswagen', 'Delphi', 141.74, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Nissan', 'TRW', 307.54, 68);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Opel', 'NGK', 457.66, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Ford', 'Bilstein', 496.5, 74);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Land Rover', 'Zimmermann', 434.58, 10);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Ford', 'TRW', 140.18, 96);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Fiat', 'TRW', 224.8, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe BMW', 'BOSCH', 486.98, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Volkswagen', 'Varta', 42.21, 10);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Porsche', 'Mann Filter', 361.92, 91);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Subaru', 'Varta', 401.55, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Renault', 'Bilstein', 338.42, 36);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Subaru', 'TRW', 282.98, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator BMW', 'Zimmermann', 28.93, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Hyundai', 'Mahle', 324.32, 13);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury BMW', 'TRW', 223.89, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Renault', 'Sachs', 310.56, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Kia', 'SKF', 32.08, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Chevrolet', 'Delphi', 435.81, 68);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Hyundai', 'Mahle', 106.27, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Toyota', 'Sachs', 454.85, 82);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Volkswagen', 'SKF', 230.35, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Volkswagen', 'SKF', 367.0, 42);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Subaru', 'Boge', 268.18, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Nissan', 'Bosch', 466.15, 70);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Hyundai', 'Valeo', 148.16, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Mazda', 'Valeo', 78.62, 51);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Mercedes', 'BOSCH', 164.43, 63);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Subaru', 'Valeo', 105.85, 82);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Peugeot', 'Lucas', 444.04, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Toyota', 'Denso', 340.97, 74);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Subaru', 'Varta', 490.38, 10);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Volkswagen', 'Varta', 487.59, 21);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Volkswagen', 'Febi Bilstein', 23.12, 97);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Audi', 'Valeo', 17.18, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Ford', 'TRW', 393.95, 97);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Mazda', 'Mann Filter', 59.93, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Nissan', 'Febi Bilstein', 443.19, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Renault', 'Denso', 281.63, 26);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Kia', 'Sachs', 88.86, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Hyundai', 'Hella', 106.81, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Mercedes', 'BOSCH', 409.57, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Mercedes', 'TRW', 166.28, 98);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Toyota', 'Bilstein', 63.46, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Renault', 'Monroe', 55.98, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Subaru', 'SKF', 307.1, 92);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Opel', 'Delphi', 118.42, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Opel', 'Mahle', 342.17, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Hyundai', 'Hella', 245.64, 82);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Mazda', 'SKF', 122.52, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'Mann Filter', 192.36, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Mercedes', 'Hella', 490.71, 32);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Nissan', 'Monroe', 301.32, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator BMW', 'BOSCH', 373.14, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Renault', 'Sachs', 244.6, 61);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Nissan', 'Boge', 175.85, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Renault', 'Brembo', 407.19, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Audi', 'Boge', 299.19, 39);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Chevrolet', 'Zimmermann', 407.68, 16);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Toyota', 'Denso', 135.29, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Opel', 'BOSCH', 400.83, 99);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Land Rover', 'Febi Bilstein', 18.47, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Kia', 'Valeo', 343.58, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Peugeot', 'Boge', 182.1, 36);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Mercedes', 'Varta', 31.24, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Toyota', 'Febi Bilstein', 105.54, 61);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Opel', 'BOSCH', 28.41, 11);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Chevrolet', 'Varta', 218.66, 35);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Porsche', 'NGK', 29.93, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Opel', 'SKF', 479.18, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Fiat', 'Hella', 149.64, 93);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Toyota', 'Febi Bilstein', 414.69, 59);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Mercedes', 'Zimmermann', 89.6, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Land Rover', 'Febi Bilstein', 468.92, 71);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Volkswagen', 'Lucas', 145.98, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Fiat', 'Monroe', 357.09, 64);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Ford', 'Sachs', 174.68, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Kia', 'TRW', 183.17, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Fiat', 'Bilstein', 212.43, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Audi', 'Mahle', 153.17, 88);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Land Rover', 'Lucas', 466.17, 8);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Jeep', 'SKF', 226.61, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Chevrolet', 'Delphi', 402.53, 77);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Hyundai', 'Lucas', 251.83, 83);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Porsche', 'Mann Filter', 136.37, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Mercedes', 'Boge', 30.75, 40);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Subaru', 'Bilstein', 46.69, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Honda', 'Lucas', 244.3, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Toyota', 'Bilstein', 162.62, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Opel', 'Valeo', 308.69, 28);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Mazda', 'Delphi', 32.98, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Mazda', 'Zimmermann', 387.08, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Ford', 'Monroe', 256.46, 59);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Audi', 'Bilstein', 285.31, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Kia', 'NGK', 65.19, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Peugeot', 'Monroe', 22.4, 28);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Porsche', 'Delphi', 454.11, 52);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Ford', 'SKF', 436.5, 99);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Land Rover', 'NGK', 379.92, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Peugeot', 'Boge', 190.71, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Nissan', 'Zimmermann', 25.62, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Fiat', 'Brembo', 266.47, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Honda', 'NGK', 191.89, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Toyota', 'Valeo', 275.86, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Nissan', 'Zimmermann', 394.76, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Kia', 'TRW', 105.52, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Hyundai', 'Lucas', 384.91, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Audi', 'Febi Bilstein', 458.53, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy BMW', 'Bosch', 486.71, 58);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Opel', 'Febi Bilstein', 20.08, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Volkswagen', 'Bilstein', 491.93, 79);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy BMW', 'Brembo', 357.07, 45);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Land Rover', 'Hella', 22.8, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Hyundai', 'Bilstein', 61.0, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Nissan', 'Bilstein', 30.07, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Audi', 'NGK', 350.83, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Ford', 'Delphi', 196.5, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Peugeot', 'Febi Bilstein', 177.61, 8);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Hyundai', 'Valeo', 259.82, 26);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Chevrolet', 'Valeo', 167.55, 26);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Porsche', 'Bosch', 313.65, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Volkswagen', 'Bilstein', 195.47, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Honda', 'Mahle', 112.96, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Chevrolet', 'SKF', 436.54, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Land Rover', 'Zimmermann', 121.32, 28);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Audi', 'Febi Bilstein', 171.94, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza BMW', 'BOSCH', 330.91, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Hyundai', 'Zimmermann', 445.27, 99);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Ford', 'Bilstein', 375.69, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi BMW', 'Boge', 264.45, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Chevrolet', 'Valeo', 308.06, 37);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Kia', 'Monroe', 154.39, 87);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Kia', 'BOSCH', 166.2, 54);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Nissan', 'Febi Bilstein', 409.45, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Honda', 'Febi Bilstein', 307.87, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Volkswagen', 'SKF', 15.6, 7);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Mercedes', 'Sachs', 333.44, 88);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Subaru', 'Lucas', 258.58, 83);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Porsche', 'Brembo', 62.4, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Ford', 'Bilstein', 237.42, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Kia', 'Mahle', 209.9, 6);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Mercedes', 'NGK', 83.47, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik BMW', 'BOSCH', 232.21, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Toyota', 'Sachs', 304.65, 79);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Land Rover', 'Monroe', 361.62, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Land Rover', 'Febi Bilstein', 456.56, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Chevrolet', 'Delphi', 484.62, 52);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Mercedes', 'Varta', 26.14, 51);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Ford', 'Brembo', 39.06, 79);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Opel', 'Bosch', 465.37, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Audi', 'Bosch', 348.7, 52);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Ford', 'NGK', 463.78, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Ford', 'Valeo', 331.48, 87);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Chevrolet', 'Boge', 27.23, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Audi', 'NGK', 150.33, 13);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Subaru', 'Varta', 448.86, 70);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Toyota', 'Febi Bilstein', 29.32, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Fiat', 'NGK', 262.05, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Hyundai', 'Zimmermann', 107.54, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Ford', 'Febi Bilstein', 330.97, 87);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Jeep', 'Valeo', 443.32, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Land Rover', 'TRW', 414.91, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Land Rover', 'Lucas', 259.54, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Volkswagen', 'Varta', 208.56, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa BMW', 'Febi Bilstein', 437.84, 46);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Subaru', 'Lucas', 311.69, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Peugeot', 'Boge', 252.85, 45);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Kia', 'Delphi', 342.5, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Mazda', 'SKF', 309.39, 79);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Nissan', 'Valeo', 450.89, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Chevrolet', 'Brembo', 350.44, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Chevrolet', 'SKF', 491.46, 44);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Volkswagen', 'Valeo', 378.87, 84);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Opel', 'BOSCH', 17.88, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Opel', 'Denso', 424.66, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Peugeot', 'Zimmermann', 452.57, 84);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Porsche', 'Boge', 346.54, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Audi', 'Lucas', 217.37, 40);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Ford', 'Mann Filter', 217.29, 7);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Peugeot', 'BOSCH', 183.21, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'Bosch', 377.1, 87);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Mercedes', 'BOSCH', 91.34, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Honda', 'Mann Filter', 420.16, 19);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Mazda', 'Bosch', 274.62, 39);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Porsche', 'Bosch', 320.07, 13);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Ford', 'Delphi', 349.47, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe BMW', 'NGK', 443.32, 87);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Peugeot', 'Brembo', 12.1, 45);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe BMW', 'Bilstein', 296.51, 83);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Honda', 'Delphi', 23.65, 76);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Honda', 'Valeo', 415.95, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Ford', 'SKF', 432.18, 16);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Audi', 'Hella', 201.39, 67);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Porsche', 'Monroe', 186.44, 84);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Toyota', 'BOSCH', 270.78, 37);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Audi', 'Lucas', 470.62, 46);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Opel', 'Mahle', 310.29, 4);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Audi', 'SKF', 332.61, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa BMW', 'Bosch', 386.56, 83);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Kia', 'Boge', 227.01, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Peugeot', 'Mahle', 75.58, 44);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Opel', 'Hella', 281.26, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Toyota', 'Bilstein', 316.66, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Audi', 'Febi Bilstein', 122.03, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Toyota', 'Bilstein', 393.28, 61);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Ford', 'SKF', 338.87, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Kia', 'Febi Bilstein', 212.67, 6);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Toyota', 'Febi Bilstein', 51.05, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Subaru', 'Lucas', 482.79, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Opel', 'TRW', 51.33, 46);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Subaru', 'Lucas', 279.75, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Opel', 'Monroe', 307.57, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe BMW', 'Bosch', 221.6, 38);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Toyota', 'Monroe', 312.55, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Peugeot', 'Monroe', 56.84, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Land Rover', 'Brembo', 396.74, 64);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Land Rover', 'Monroe', 27.73, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Land Rover', 'Zimmermann', 232.66, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Jeep', 'Delphi', 129.76, 83);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Jeep', 'Valeo', 320.83, 58);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Audi', 'Hella', 495.98, 45);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Volkswagen', 'Denso', 24.94, 54);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Chevrolet', 'SKF', 176.77, 11);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Honda', 'Bosch', 323.16, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Mercedes', 'Febi Bilstein', 439.9, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Audi', 'NGK', 228.05, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Honda', 'TRW', 258.19, 64);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Mercedes', 'Denso', 95.49, 20);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Kia', 'Febi Bilstein', 84.32, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Renault', 'Boge', 483.23, 96);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Mercedes', 'Hella', 281.11, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Subaru', 'NGK', 47.45, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Chevrolet', 'Valeo', 388.96, 96);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury BMW', 'Varta', 225.31, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Chevrolet', 'Mann Filter', 230.46, 69);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Ford', 'Mann Filter', 215.05, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Kia', 'BOSCH', 179.69, 27);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Volkswagen', 'Febi Bilstein', 315.09, 42);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Subaru', 'Denso', 172.42, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Land Rover', 'Varta', 77.78, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Hyundai', 'Mahle', 94.39, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Ford', 'Febi Bilstein', 130.42, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Ford', 'BOSCH', 19.99, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Mercedes', 'Delphi', 389.77, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Audi', 'Varta', 146.53, 59);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Honda', 'SKF', 92.24, 61);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Mazda', 'Valeo', 62.65, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Toyota', 'Bilstein', 114.19, 21);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Land Rover', 'Bosch', 394.61, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'Monroe', 23.77, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Volkswagen', 'Mahle', 162.37, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Toyota', 'Lucas', 353.42, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Mazda', 'Boge', 38.81, 30);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Chevrolet', 'Brembo', 487.97, 70);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Volkswagen', 'Mahle', 256.57, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Opel', 'Mann Filter', 292.63, 91);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Renault', 'NGK', 149.39, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Honda', 'Varta', 395.87, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Fiat', 'Bosch', 198.64, 32);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Hyundai', 'Varta', 339.53, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Kia', 'Denso', 30.85, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Kia', 'Febi Bilstein', 230.04, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Mercedes', 'Hella', 309.67, 32);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Jeep', 'Zimmermann', 489.32, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Subaru', 'Sachs', 235.64, 92);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Jeep', 'Boge', 333.25, 26);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Honda', 'Lucas', 133.21, 50);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Audi', 'Valeo', 410.88, 96);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Mercedes', 'Bosch', 34.34, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Mercedes', 'Brembo', 234.09, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Volkswagen', 'BOSCH', 409.16, 73);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Toyota', 'Hella', 144.53, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Chevrolet', 'Varta', 67.44, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Jeep', 'Bilstein', 191.06, 80);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Chevrolet', 'Bosch', 400.7, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Nissan', 'Mahle', 319.03, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Opel', 'Hella', 142.28, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Chevrolet', 'Zimmermann', 48.67, 37);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Nissan', 'Valeo', 30.02, 26);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Honda', 'Bosch', 108.0, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Fiat', 'NGK', 287.04, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Porsche', 'Sachs', 358.69, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Kia', 'Varta', 299.7, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Ford', 'TRW', 103.56, 42);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Nissan', 'Lucas', 294.32, 63);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Chevrolet', 'Varta', 456.37, 11);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Jeep', 'NGK', 14.61, 36);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Opel', 'Monroe', 234.22, 12);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Fiat', 'Mahle', 403.23, 72);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Subaru', 'Hella', 188.38, 56);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Renault', 'Bosch', 452.68, 37);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Renault', 'NGK', 213.45, 56);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Porsche', 'Mann Filter', 172.81, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Mercedes', 'TRW', 436.39, 77);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Peugeot', 'Varta', 16.11, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Chevrolet', 'Delphi', 365.93, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Kia', 'TRW', 225.1, 1);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Nissan', 'Monroe', 462.79, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Nissan', 'BOSCH', 160.42, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Hyundai', 'NGK', 337.74, 53);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Honda', 'Sachs', 177.69, 81);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Peugeot', 'Boge', 96.94, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Land Rover', 'Valeo', 210.83, 18);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Subaru', 'Zimmermann', 104.19, 57);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Renault', 'Boge', 197.44, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Mazda', 'TRW', 454.36, 67);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Subaru', 'TRW', 62.09, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Nissan', 'Lucas', 77.85, 68);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Mercedes', 'Bilstein', 254.54, 62);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Hyundai', 'SKF', 212.1, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury BMW', 'Delphi', 321.05, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Peugeot', 'Valeo', 257.11, 39);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Opel', 'Sachs', 484.09, 74);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Volkswagen', 'Lucas', 115.47, 8);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Opel', 'Bilstein', 205.93, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Kia', 'TRW', 391.73, 23);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Opel', 'Febi Bilstein', 192.33, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Porsche', 'Denso', 429.67, 13);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Mercedes', 'Febi Bilstein', 186.84, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Mercedes', 'Lucas', 54.33, 38);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Chevrolet', 'Boge', 392.21, 100);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Opel', 'Monroe', 264.98, 11);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Porsche', 'Varta', 366.62, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Chevrolet', 'Varta', 302.42, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Mercedes', 'Lucas', 489.45, 20);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Renault', 'Mann Filter', 485.93, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Mazda', 'Zimmermann', 56.36, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Toyota', 'Valeo', 265.39, 31);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Jeep', 'Mann Filter', 177.48, 21);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe BMW', 'Denso', 277.65, 43);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Mercedes', 'Hella', 38.83, 64);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Kia', 'Brembo', 419.19, 60);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Land Rover', 'Bilstein', 236.92, 7);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Porsche', 'Delphi', 251.39, 78);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr oleju Porsche', 'Delphi', 416.59, 85);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Hyundai', 'Mann Filter', 496.65, 32);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Fiat', 'Zimmermann', 124.59, 15);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Peugeot', 'Sachs', 362.52, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Mercedes', 'Sachs', 153.81, 44);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Amortyzator Kia', 'Zimmermann', 150.23, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Audi', 'Bilstein', 276.64, 5);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Nissan', 'Denso', 272.07, 95);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Hyundai', 'TRW', 410.36, 100);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Audi', 'Sachs', 340.94, 39);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Filtr powietrza Honda', 'Sachs', 23.49, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Subaru', 'Sachs', 114.9, 16);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Audi', 'SKF', 117.31, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Ford', 'NGK', 112.5, 3);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Jeep', 'TRW', 201.92, 17);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wal korbowy Peugeot', 'Mahle', 452.31, 9);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Sprzeglo Porsche', 'Sachs', 27.27, 65);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Peugeot', 'Febi Bilstein', 64.41, 84);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Nissan', 'Monroe', 345.42, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Renault', 'Boge', 154.25, 75);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Audi', 'Lucas', 416.88, 33);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tlumik Chevrolet', 'Valeo', 282.41, 29);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Wymiennik ciepla Fiat', 'Monroe', 287.86, 94);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Honda', 'TRW', 255.79, 59);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Opel', 'Brembo', 72.07, 49);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Toyota', 'Hella', 160.63, 48);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Mazda', 'SKF', 464.84, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Mazda', 'Sachs', 40.02, 82);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Mazda', 'Sachs', 436.27, 100);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Porsche', 'Febi Bilstein', 327.95, 66);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy BMW', 'Monroe', 324.94, 30);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Peugeot', 'Sachs', 47.82, 80);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod zaplonowy Volkswagen', 'Varta', 419.18, 63);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Jeep', 'Varta', 182.18, 59);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Alternator Land Rover', 'Hella', 318.17, 61);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Chevrolet', 'Hella', 292.77, 38);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Mazda', 'Boge', 174.62, 11);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Chlodnica Mazda', 'Monroe', 339.94, 22);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod chlodnicy Toyota', 'SKF', 479.65, 86);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Subaru', 'Varta', 155.38, 89);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Mercedes', 'Febi Bilstein', 394.19, 55);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pasek rozrzadu Peugeot', 'Boge', 125.1, 90);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Kia', 'Denso', 459.25, 41);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Zamek drzwi Peugeot', 'BOSCH', 285.88, 98);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Przewod hamulcowy Chevrolet', 'Sachs', 244.51, 63);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Czujnik temperatury Hyundai', 'Boge', 385.64, 24);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Fiat', 'Valeo', 333.64, 20);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Swiece zaplonowe Jeep', 'Monroe', 399.54, 47);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Klocki hamulcowe Fiat', 'Boge', 484.45, 25);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Akumulator Hyundai', 'Mann Filter', 324.9, 34);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Tarcza hamulcowa Toyota', 'Hella', 326.99, 14);
INSERT INTO CzesciSamochodowe (Nazwa, Producent, Cena, IloscNaStanie) VALUES ('Pompa paliwa Honda', 'Delphi', 485.51, 62);
